Repository Automattic/happychat-client, pull requests merged in 2018-08, with the labels that each got.

#258 Reorder first messages sent to operators
  src/form.js
Labels: [Target] Core

#259 fix product dropdown closing when user clicks in search box
  src/ui/components/select-dropdown/index.jsx
  src/ui/components/select-dropdown/test/index.js
Labels: [Status] Needs Review, [Type] Bug

#264 Fix/bind class methods
  src/ui/components/contact-form/index.jsx
  src/ui/components/emojify/index.jsx
  src/ui/components/form-text-input/index.jsx
  src/ui/components/notices/index.jsx
  src/ui/components/select-dropdown/index.jsx
  src/ui/components/select-dropdown/search.jsx
Labels: [Type] Bug
