Repository Automattic/happychat-client, pull requests merged in 2018-06, with the labels that each got.

#231 Update/socket.io client to 2.1.1
  .nvmrc
  circle.yml
  package-lock.json
  package.json
Labels: [Status] Needs Review

#241 Add/theme property
  docs/API.md
  docs/HACKING.md
  src/api.js
  src/index.js
  targets/standalone/example.html
Labels: [Target] Core

#243 lodash: import module not the full library
  src/ui/components/form-description/index.jsx
Labels: Performance

#246 Allow hosts to customize text for submitButton
  docs/API.md
  src/form.js
  targets/standalone/example.html
Labels: [Target] Core

#248 Update CircleCI config v2 npm ci
  circle.yml
Labels: [Status] Needs Review

#249 Update to react 16
  .nvmrc
  package-lock.json
  package.json
  setup-jest.js
Labels: Needs Devexp, Performance

#250 Update/redux
  package-lock.json
  package.json
Labels: Needs Devexp

#251 Update/misc deps
  package-lock.json
  package.json
Labels: Needs Devexp
