Repository Automattic/happychat-client, pull requests merged in 2018-04, with the labels that each got.

#187 Add/themes
  docs/HACKING.md
  package.json
  src/form.scss
  src/index.js
  src/ui/components/button/style.scss
  src/ui/components/card/style.scss
  src/ui/components/composer/style.scss
  src/ui/components/count/style.scss
  src/ui/components/happychat-form/style.scss
  src/ui/components/notices/style.scss
  src/ui/components/segmented-control/style.scss
  src/ui/components/select-dropdown/style.scss
  src/ui/components/spinner-line/style.scss
  src/ui/components/timeline/style.scss
  src/ui/components/title/style.scss
  src/ui/css/_main.scss
  src/ui/css/shared/_color-schemes.scss
  src/ui/css/shared/_colors.scss
  src/ui/css/shared/_forms.scss
  src/ui/css/shared/_typography.scss
  src/ui/css/themes/_jpop.scss
  src/ui/css/themes/_main.scss
  src/ui/css/themes/_woo.scss
  targets/dist/happychat.css
  targets/dist/happychat.js
  targets/dist/jpop.css
  targets/dist/woo.css
  targets/standalone/public/happychat.js
  targets/standalone/public/index.html
  targets/wordpress/assets/happychat.js
Labels: Needs Design, [Status] In Progress

#176 Extract api and use different entry points
  index.js
  src/api.js
  src/index.js
  targets/dist/happychat.css
  targets/dist/happychat.js
  targets/dist/index.js
  targets/standalone/index.js
  targets/standalone/public/happychat.js
  targets/standalone/public/index.html
  targets/wordpress/assets/happychat.js
  targets/wordpress/index.js
  webpack.dist.config.js
  webpack.wordpress.config.js
Labels: [Status] Ready to Merge

#180 Add local config files
  docs/HACKING.md
  src/config/README.md
  src/config/index.js
  src/index.js
  targets/standalone/index.html
Labels: [Status] Ready to Merge

#184 Add support for npm package
  .babelrc
  README.md
  bin/fix-local-config.js
  circle.yml
  jest.config.json
  package-lock.json
  package.json
  src/config/index.js
  targets/npm/.gitignore
  webpack.npm.config.js
Labels: [Status] Needs Review

#191 Fix bundler analyzer
  package.json
  webpack.cdn.config.js
  webpack.npm.config.js
  webpack.standalone.config.js
  webpack.wordpress.config.js
Labels: [Status] Needs Review

#192 Clean up targets
  README.md
  docs/HACKING.md
  package.json
  src/config/development.json
  targets/README.md
  targets/cdn/index.js
  targets/standalone/config/index.js
  targets/standalone/example.html
  targets/standalone/index.js
  targets/standalone/public/index.html
  webpack.cdn.config.js
  webpack.standalone.config.js
Labels: [Status] Needs Review

#188 Add support for wpcom proxy auth
  src/config/development.json
  src/config/production.json
  src/lib/auth/README.md
  src/lib/auth/index.js
  src/lib/auth/strategies/index.js
  src/lib/auth/strategies/wpcom/index.js
  src/lib/auth/strategies/wpcom/oauth.js
  src/lib/auth/strategies/wpcom/proxy-iframe.js
  targets/standalone/example.html
  targets/standalone/index.js
Labels: [Status] Needs Review

#198 Rename variable as the previous one was not defined
  targets/wordpress/class-happychat-client.php
Labels: [Status] Needs Review

#205 Fix/happychat
  package.json
  src/config/development.json
  webpack.wordpress.config.js
Labels: Needs Devexp
